### ISSUE TITLE
Fatal error when there is some specific arabic symbol in the codebase

### ISSUE THREAD

**Issue by sergiy-petrov** [VKCOM/noverify#17]
## Code Example

```php
<?php


$baseText = <<<'EOT'
  ‌ا
EOT;

```

## Actual Behavior

If there is  ‌ا symbol in EOT directive - noverify will be fallen down. 
Please, find below console output:
https://justpaste.it/4fzm4

## Expected Behavior

All OK

## Environment

- NoVerify Version: dev-master
- Operating System: Linux, Ubuntu 16.04
- Go version go1.12 linux/amd64

**Comment by cixtor** [comment]
The bug actually happens inside [z7zmey/php-parser in lexer.go line 514](https://github.com/VKCOM/noverify/blob/99f68128125b390e9fc58a78147ffbf35b15dec4/vendor/github.com/z7zmey/php-parser/scanner/lexer.go#L514) because it’s trying to access index zero in an array of characters that is empty.

I was going to patch this bug upstream, but it seems that modified “php-parser” for this project, so the two repositories are not compatible anymore. Maybe a simple update of this dependency will resolve the problem. I tried to update to master, but then it started complaining that it cannot find package “z7zmey/php-parser/comment” which doesn’t exists anymore.

**Comment by YuriyNasretdinov** [comment]
Yes, that is a bug in php-parser and it is not too easy to update the dependency version as library API is not yet stable :(. I plan to do this in the future though.

**Comment by quasilyte** [comment]
It still fails with a newer php-parser version.

**Comment by quasilyte** [comment]
We updated PHP parser and now there should be no panics.
