### ISSUE TITLE
Exclude does not exclude

### ISSUE THREAD

**Issue by Danil42Russia** [VKCOM/noverify#22]
## Steps
1)Execute `go get -u github.com/VKCOM/noverify`
2)Execute
```
-stubs-dir=D:\Libs\phpstorm-stubs -cache-dir=D:\tmp\noverify -exclude='(vendor|test)' D:\Dev\php\TestProject
```

## Actual
Folders from the exception get into the report

## Expected
All OK

## Fix
Use **-exclude=(vendor|test)** or **-exclude="(vendor|test)"**

**Comment by YuriyNasretdinov** [comment]
In UNIX you definitely cannot use `-exclude=(vendor|test)` without quotes because of the special meaning of pipe `|` operator. You can, however, use double quotes here, although single quotes are better for regular expressions. I will adjust documentation a little bit, but that actually is a Windows terminal issue, not issue with linter itself.
