### ISSUE TITLE
Philosphical: who is this project for

### ISSUE THREAD

**Issue by muglug** [VKCOM/noverify#331]
Hey!

I just read [the article](https://medium.com/@vktech/noverify-dynamic-rules-for-static-analysis-8f42859e9253) and I'm curious about this line:

> NoVerify is a static analysis tool that helps VK developers

Is the intent that it might be used more widely, or are VK developers likely to be the only consumers?

**Comment by YuriyNasretdinov** [comment]
Noverify was made as a general-purpose static analyser for PHP that has sufficient performance to be able to check VK codebase quickly enough (VK codebase is pretty old and relied heavily on global variables and functions, so existing linters just refused to work in this scenario). While it is much better tested on VK codebase the intention is to actually support a full set of features that PHP has.

**Comment by muglug** [comment]
Yeah, it seems tuned only for a fairly legacy “in-house style”. Running it on two modern PHP codebases — Vimeo’s internal one, and https://github.com/vimeo/psalm — shows a ton of false-positives.

Also, separately, I was only able to replicate the performance benefits on Psalm’s codebase (where it takes 2s vs 8s for Psalm). Running on Vimeo’s codebase (800K LOC) it took the same amount of time as when running Psalm - it looks like it was unable to parallelise its analysis in the latter case. Happy to dig into that further if it helps!

**Comment by quasilyte** [comment]
> Happy to dig into that further if it helps!

It will definitely help.

We try to fix false positives as fast as possible when they're reported. It's just hard to know about all of them if they're not recorded in this issue tracker.

**Comment by muglug** [comment]
Well you can reproduce the Psalm false-positives yourself, as the code’s public.

I was talking about the lack of parallelism while analysing Vimeo’s internal one - is that something you’ve come across before?

**Comment by quasilyte** [comment]
> Well you can reproduce the Psalm false-positives yourself, as the code’s public.

I can and probably will. But it requires some time to categorize them and prepare minimal reproducers that make it easier to understand what would be the best fix to the problem.

Were you using `-cache-dir` option for noverify? It should make the next linting much faster.

**Comment by muglug** [comment]
> Were you using -cache-dir option for noverify? It should make the next linting much faster.

Nop I wasn’t, and that makes a lot of sense.

**Comment by muglug** [comment]
> it requires some time to categorize them and prepare minimal reproducers that make it easier to understand what would be the best fix to the problem.

FYI Psalm has tons of tests in a reasonably self-explanatory format. It wouldn’t be too hard for you to extract a lot of them into your own test suite (especially the assumed-to-be-valid-code ones in `tests/TypeReconciliation`)

**Comment by YuriyNasretdinov** [comment]
> I was talking about the lack of parallelism while analysing Vimeo’s internal one - is that something you’ve come across before?
Did using cache-dir change the performance characteristics? Because otherwise noverify basically processes all the files twice (the primary use case for VK is to analyse diff instead of the full project so having a separate index makes sense).
There should be no issues in regards to parallelism though: if you run `time noverify` it should show you that it was using most of the cores most of the time. If it is not the case then please file a separate bug because noverify architecture should not have any parts other than updating the global in-memory index that are not run in parallel.

**Comment by muglug** [comment]
(update to the above: https://github.com/VKCOM/noverify/issues/333 helped narrow down the performance issue)

**Comment by muglug** [comment]
I think I got what I needed from this, and given the results of [this poll](https://twitter.com/psalmphp/status/1219723750603661312) it looks like Psalm won't be switching to Go anytime soon.

Nevertheless, a lot of [the open issues](https://github.com/VKCOM/noverify/issues) are things that are fixed in Psalm – I'd encourage you to use some of the same approaches – especially around type inference, which I've spent months refining over the years. Happy to explain them in more detail if you have questions.

**Comment by YuriyNasretdinov** [comment]
Sure, I personally also don't think trying to translate PHP to Go would yield good results as the architecture for Go should make use of shared memory and parallelism from the start, as well as account for Go's strengths and weaknesses.

E.g. noverify does not require you to annotate functions and methods with PHPDoc if it can prove that a function has a certain type, e.g.

```
<?php
function a() {
return new DateTime();
}

function a() {
return new stdclass();
}

// some other file

function b() {
return rand() ? a() : c();
}

// yet another file

function d() {
return b()->some_property; // noverify will complain about (DateTime|stdclass)->some_property missing)
}
```

This is possible because Go is so much faster than PHP in brute-force operations. I am not sure if Psalm will work in similar cases for example.

I'll try to take a closer look to the issues that arise in Psalm test cases in the future and see if we can easily fix the found issues as it will definitely improve `noverify` code analysis quality too.

**Comment by YuriyNasretdinov** [comment]
Also I don't think all warnings that noverify gives about the codebase in Psalm are false positives. I opened the first file in alphabetical order (AlgebraTest.php) in language server mode (it is much more convenient to use for debugging the linter issues compared to CLI invocation IMO) and it did show some issues that I would not classify as false positives, e.g.

![Screen Shot 2020-01-22 at 00 19 08](https://user-images.githubusercontent.com/575929/72854728-20788700-3cad-11ea-984b-2b2b1ca838e2.png)

**Comment by muglug** [comment]
> E.g. noverify does not require you to annotate functions and methods with PHPDoc if it can prove that a function has a certain type 

Yeah, Phan can do some of that same introspection. The thing is, it’s normally better to have well-annotated functions to begin with, so Psalm comes with a fixer that adds return types to methods (either in PHPDoc or in the signature) so the code is made better even if no bugs were discovered.

This is (again) more of a philosophical difference - I imagine that when they created Phan, Etsy’s engineers were dealing with a codebase that lacked a lot of docblocks, so this seemed like the best approach at the time, too.

Still, that’s a fairly niche issue - when I’m talking about type inference, I refer more to Psalm’s ability to reconcile complex conditionals, understand assignments in those conditionals and inside loops. That’s the stuff that has taken years to get (reasonably) right.

**Comment by muglug** [comment]
> Also I don't think all warnings that noverify gives about the codebase in Psalm are false positives.

From the PHPUnit docs:

> A common question, especially from developers new to PHPUnit, is whether using `$this->assertTrue()` or `self::assertTrue()`, for instance, is “the right way” to invoke an assertion. The short answer is: there is no right way. And there is no wrong way, either. It is a matter of personal preference.

There is absolutely no harm in calling a static method as if it were an instance method – it is absolutely valid PHP. Calling an instance method as if it were a static method is very bad.

**Comment by YuriyNasretdinov** [comment]
Yeah, I agree, understanding code flow seems like a challenging issue, definitely. Probably noverify will also need years of polishing before it could understand the control flow well enough :).

Also I found a lot of issues to be related to usage of list<type> or non-empty-list<type> annotations, for example, that `noverify` interprets as classes instead (I haven't seen these annotations before...). When annotations like this are replaced with more "standard" (by standard I mean that it is what I am used to) `type[]` or `type[][]`, the problems go away.

So it might be interesting to see how many issues are left after dealing with simple issues like this. Probably still a lot :).

> There is absolutely no harm in calling a static method as if it were an instance method – it is absolutely valid PHP. Calling an instance method as if it were a static method is very bad.

Sure, it makes sense, especially in PHPUnit code. I still don't agree that it's fine to call static methods as instance ones and vice versa though even if it is technically vallid PHP :). Calling an instance method as a static one is just deprecated apparently (for some reason I thought that it would cause a fatal error immediately, but apparently it only happens if you use `$this` inside the method).

![Screen Shot 2020-01-22 at 00 29 08](https://user-images.githubusercontent.com/575929/72855165-7ef23500-3cae-11ea-8c7d-13684f42cdf8.png)

**Comment by muglug** [comment]
> I still don't agree that it's fine to call static methods as instance ones _and vice versa_

I didn't say that – I said "Calling an instance method as if it were a static method is very bad."

**Comment by muglug** [comment]
vis-a-vis types-with-dashes: those are illegal in PHP – there are a few `OCI-` extension classes that are grandfathered in, but basically any tool that cannot support them should just ignore them.

**Comment by YuriyNasretdinov** [comment]
Thanks for clarification on types-with-dashes!

**Comment by quasilyte** [comment]
Can we consider this issue to be resolved?

**Comment by muglug** [comment]
Yes!

**Comment by quasilyte** [comment]
Nice. Feel free to open new issues if you have any more questions/suggestions or bug reports.
