### ISSUE TITLE
Flag to disable exclusion of changes to master

### ISSUE THREAD

**Issue by setpill** [VKCOM/noverify#347]
## Code Example

We use `noverify` with the following command in our CI setup:

```
- noverify \
	-git=.git \
	-git-skip-fetch \
	-git-commit-from=`git merge-base origin/master $COMMIT_SHA` \
	-git-commit-to=$COMMIT_SHA \
	-git-ref=refs/heads/$BRANCH_NAME \
	-cache-dir=$HOME/tmp/cache/noverify
```

## Actual Behavior

`Could not compute merge base between ORIGIN_MASTER and $LATEST_MASTER_COMMIT`

## Expected Behavior

For it to work without complaining. Seems it is trying to be too smart by (according to [the docs](https://github.com/VKCOM/noverify/tree/2f81ae701ae5b3b932d1d2480b3838f1223a5a91https://github.com/VKCOM/noverify/blob/master/docs/linter-usage.md)) "excluding changes made to master branch that is fetched to ORIGIN_MASTER". We want to use this tool to check files changed in a MR - regardless of what happened on master since. Therefore, files changed on master do not need to be excluded.

**Comment by YuriyNasretdinov** [comment]
You can already achieve that by specifying `-git-ref=refs/heads/master` instead of `-git-ref=refs/heads/$ref` but I agree that providing an explicit option would be better.

Initially we didn't have exclusion of changes made in master but it made it impossible for us to enable noverify gradually for certain teams / people because if in the MR/PR there were merges from master that caused warnings they would also be shown during the push. As noverify at VK is set up as a blocking pre-push hook it was a problem so excluding master by default was the solution that was chosen.

**Comment by setpill** [comment]
I tried your suggestion but it gives the same error. Included below is the command as run:

```
$ noverify -git=.git -git-skip-fetch -git-commit-from=`git merge-base origin/master $COMMIT_SHA` -git-commit-to=$COMMIT_SHA -git-ref=refs/heads/master -cache-dir=$HOME/tmp/cache/noverify
```

**Comment by YuriyNasretdinov** [comment]
Hm, it turns out that this logic was removed by myself some time ago so you currently can't disable it. So I am not sure, but probably the best that you can do now is to make ORIGIN_MASTER to point to your `-git-from-commit` value so that no changes are excluded. From my understanding it should be something like ```
git update-ref ORIGIN_MASTER `git merge-base origin/master $COMMIT_SHA`
```

The longer term solution is to actually introduce a new flag to do this, of course, so this bug should remain open until we implement it.

**Comment by setpill** [comment]
Hmm, from my understanding this error is caused by my `-git-from-commit` being equal to `ORIGIN_MASTER`, so that doesn't seem like it would work. `ORIGIN_MASTER` is *already* the same commit as the output of my `git merge-base`.

**Comment by setpill** [comment]
Turns out there was something else entirely going on. I had not understood that `ORIGIN_MASTER` was a special ref populated by `noverify`; I knew that `origin/master` had been updated earlier in the script so had enabled `-git-skip-fetch`; but, as it turns out, this caused `ORIGIN_MASTER` to not exist resulting in `git merge-base` returning `fatal: Not a valid object name ORIGIN_MASTER`. More verbose output of `git merge-base` revealed this.

So, some pebcak, but also some strange behaviour in the code (why use `ORIGIN_MASTER` when `origin/master` exists?). I have fixed my problem but leaving this open for potential improvement; feel free to close if desired.

**Comment by YuriyNasretdinov** [comment]
In regards to why there exists a separate branch called `ORIGIN_MASTER` instead of using origin/master, the reason is very simple: by doing `git fetch origin master:ORIGIN_MASTER` we can make sure that it is up-to-date. Git didn't use to update `origin/...` branches when calling commands like `git pull origin master` for example  (it got much better since then but it is not entirely clear to me when those branches are updated). When origin/master is not up-to-date the changes from master won't be excluded properly which leads to very hard-to-diagnose bugs.

**Comment by setpill** [comment]
I suspected it would be something like that, thanks for confirming. What I said about strange behaviour I should have worded as *unexpected* behaviour - not because it is wrong or illogical, but because I did not expect it works that way. Looking back at the docs, the signs were there, I simply did not pick up on them because I had simply assumed `ORIGIN_MASTER` to be a different way of writing `origin/master`.

**Comment by YuriyNasretdinov** [comment]
Sure, we'll think how to improve docs and allow to not exclude master too. Thank you for the feedback!

**Comment by setpill** [comment]
In my debugging I already wrote some code to not exclude master. Let me see if it works, I'll open a PR if it does.

**Comment by setpill** [comment]
Though; seeing as it's not what broke my workflow, I am not 100% sure it actually has a usecase. I will open it if you think it does, but maybe it just adds unneeded complexity to the code.

**Comment by setpill** [comment]
Improved documentation tracked in #349; closing this.
