### ISSUE TITLE
how to check only some  errors "undefined" - in example 'ERROR   undefined: Class not found'

### ISSUE THREAD

**Issue by 6umpukc-uHKBu3umop** [VKCOM/noverify#351]
i have very messy legacy php code
and this code is work!

but if  i try to simple check of one single file - this produces a bunch of errors

```
<critical> ERROR   undefined: Call to undefined method {\Bitrix\Main\Entity\Base}->getDataClass() at ...
<critical> ERROR   undefined: Call to undefined method {mixed}->registerRuntimeField() at ...
<critical> ERROR   undefined: Call to undefined method {mixed}->setSelect()...
...
```
i can't rewrite this code
so i need to disable this check for annoying errors like "undefined method" for "dynamic" usings

 but i need check errors like
-  "undefined: Class not found"
- "Class constant \CheckboxWidget::TYPE_BOOLEAN does not exist"
- "static Class method \CheckboxWidget::render does not exist"
and other  "static" usings of classes and functions errors

how i can do this?

**Comment by quasilyte** [comment]
It's probably related to #83.
We can start from a mode that treats `mixed` usages in a more conservative way.
There is a chance that this will be implemented, but we lack users' feedback on it. I would also like to see more @YuriyNasretdinov thoughts on it before it's actually done.

Luckily, there is another way:
1. Don't run checks on the code that you can't modify.
2. Inside your code, when you have mixed-typed value, annotate it with `@var` or `@param`, depending on the context.

The benefit is that your code is more IDE-friendly and static analysis tools can do more for you.

Here are some examples that can be helpful:
```php
// Suppose we have 3rd party foo function that returns mixed result.
function foo() {}

// This is error-prone and linter will trigger a warning:
$x = foo();
$x->bar(); // Error, calling {mixed}->bar()

// Solution 1: use instanceof to ensure that $x has bar method:
$x = foo();
if ($x instanceof CanDoBar) {
  $x->bar();
}

// Solution 2: do a call-site var annotation
/** @var CanDoBar */
$x = foo();
$x->bar(); // No error.

// Solution 3: wrap the function with a proper types info.
// Use wrapper function inside your code.
/** @return CanDoBar */
function my_foo() { return foo(); }
```

Solutions 1 and 2 are adhoc and only suitable if `foo` is called in 1-2 places. If it's a frequently used function, it's better to write a wrapper function.

Classes and methods/static methods are essentially the same for this. You need a typed wrapper or annotate local variable.

**Comment by YuriyNasretdinov** [comment]
> We can start from a mode that treats mixed usages in a more conservative way.

I don't agree that it's a great idea to do that by default. By allowing `{mixed}->anything()` by default we are not able to check that methods still exist after refactoring those methods, for example, and it also introduces other false positives that are even weirder than the original one:

Consider the following piece of code, for example:

```
<?php
class A {
public function b(&$c) {
$c = 1;
}
}

$class_name = 'A';
(new $class_name)->b($c);
```

Currently this code emits two warnings when it does not know the type (and 0 warnings when the type is known):
1) call to undefined method `{}->b()`
2) undefined variable `$c`

If we remove warning (1) it will just complain about (2) and not complain when methods actually don't exist. So we will still have false-positives and give authors false sense of security because noverify passes the checks.

I think that the better idea is to allow to use option like '-ignore-mixed-instance-expressions' or something like that and suggest to use that when we detect this use-case but make sure that the users understand what issues this flag might cause before using (preferrably print a warning about this option upon every noverify invocation).

In regards to how to solve the immediate problem of not having proper annotations in the code I would suggest to use diff mode instead and slowly fix the code and the annotations as they come. There is usually no need to rewrite the legacy (and production-tested) code anyway apart from maybe adding type annotations there.

It is also possible to create wrapper functions as well as have a separate file/directory just for indexing purposes that would define the necessary functions with all the annotations but I would say that a much better idea is to actually submit PRs to the original libraries that add type annotations as otherwise you're not really fixing anything.
