### ISSUE TITLE
support for class_alias

### ISSUE THREAD

**Issue by 6umpukc-uHKBu3umop** [VKCOM/noverify#361]
example of aliases

https://bitbucket.org/6umpukc/microframework/src/master/bitrix/modules/main/include/compatibility.php#lines-47

`class_alias('Bitrix\Main\ORM\Data\DataManager', 'Bitrix\Main\Entity\DataManager');`

have error 

```
<critical> ERROR   undefined: Call to undefined method \X\Y\Data\ProfileLogTable::getList() at /home/bitrix/ext_www/site1.local/bitrix/modules/my.solution/lib/export/vkontakte.php:185
		$logIterator = ProfileLogTable::getList([
		                             ^^^^^^^
```

https://bitbucket.org/6umpukc/microframework/src/master/bitrix/modules/main/lib/orm/data/datamanager.php

and have class extended from alias `Bitrix\Main\Entity\DataManager ` (not original `Bitrix\Main\ORM\Data\DataManager`)
```
class ProfileLogTable extends Main\Entity\DataManager
{
```

**Comment by YuriyNasretdinov** [comment]
This is a an interesting case. I think we can create a new label that should be called something like "long tail" or something like that. Because I haven't really seen anyone use `class_alias` in their code before even though I have been programming in PHP for 10+ years :), but I know that this function exists.

The purpose of linter is not necessarily to support 100% of what PHP is capable of, but rather to support the "modern" and "good practice" cases. In this case I agree that it would be great if `noverify` would support `class_alias` but I am also sure that it should also complain about this function and advise not to use it :).

**Comment by 6umpukc-uHKBu3umop** [comment]
unfortunately this is used in the bitrix cms core - which have many legacy code

any workaround for solving this problem?

**Comment by YuriyNasretdinov** [comment]
The workaround is really simple: just define `namespace Bitrix\Main\Entity; class DataManager extends \Bitrix\Main\ORM\Data\DataManager {} ` in some file that is not used in production code and noverify will pick it up.

Noverify will treat those classes as basically the same although you might face some issues but I am pretty sure that it will be the case with future versions of PHP anyway :).

**Comment by 6umpukc-uHKBu3umop** [comment]
I think this is enough
thanks
